version: '3'

vars:
  GREETING: Hello, Blade!

tasks:
  default:
    desc: Example
    silent: true
    vars:
      PROFILE: Release
    cmds:
      - echo "{{.GREETING}}"
      - task: setup
      - task: build
        vars:
          PROFILE: '{{.PROFILE}}'
      - task: run
        vars:
          PROFILE: '{{.PROFILE}}'

  start:  
    vars:
      PROFILE: Debug
    cmds: 
      - task: build
        vars:
          PROFILE: '{{.PROFILE}}'
      - task: run
        vars:
          PROFILE: '{{.PROFILE}}'

  setup:
    vars:
      BUILD_FOLDER: '{{.BUILD_FOLDER | default "cmake-build-vs"}}'
    cmds: 
      - cmake -S . -B {{.BUILD_FOLDER}} -G "Visual Studio 17 2022" -A x64

  build:
    internal: true
    vars:
      BUILD_FOLDER: '{{.BUILD_FOLDER | default "cmake-build-vs"}}'
      PROJECT: '{{.PROJECT | default "Example"}}'
      PROFILE: '{{.PROFILE | default "Debug"}}' # 'Release'
    cmds:
      - cmake --build {{.BUILD_FOLDER}} --target {{.PROJECT}} --config {{.PROFILE}}

  run:
    internal: true
    vars:
      BUILD_FOLDER: '{{.BUILD_FOLDER | default "cmake-build-vs"}}'
      PROJECT: '{{.PROJECT | default "Example"}}'
      # 'Release' it defaults to 'Debug'
      PROFILE: '{{.PROFILE | default "Debug"}}'
    cmds:
      - ./{{.BUILD_FOLDER}}/{{.PROJECT}}/{{.PROFILE}}/{{.PROJECT}}.exe