version: '3'

vars:
  GREETING: Hello, Blade!

tasks:
  default:
    desc: Example
    silent: true
    cmds:
      - echo "{{.GREETING}}"
      - task: setup
      - task: build
        vars:
          PROFILE: Release
#      - ./cmake-build-vs/Example/Debug/Example.exe

  run:
    cmds: 
      - task: build
        vars:
          PROFILE: Debug
      - ./cmake-build-vs/Example/Debug/Example.exe

  setup:
    vars:
      BUILD_FOLDER: '{{.BUILD_FOLDER | default "cmake-build-vs"}}'
    cmds: 
      - cmake -S . -B {{.BUILD_FOLDER}} -G "Visual Studio 17 2022" -A x64

  build:
    vars:
      BUILD_FOLDER: '{{.BUILD_FOLDER | default "cmake-build-vs"}}'
      PROJECT: '{{.PROJECT | default "Example"}}'
      # 'Release' it defaults to 'Debug'
      PROFILE: '{{.PROFILE | default "Debug"}}'
    cmds:
      - cmake --build {{.BUILD_FOLDER}} --target {{.PROJECT}} --config {{.PROFILE}}
